title = "Конфигурация табло со списком роботов"

[[broker]]
mqtt_host = "10.0.10.185"
mqtt_port = 9001

# local this
[[broker]]
mqtt_host = "192.168.1.120"
mqtt_port = 9001

[robots]
count = 10
direction = ["L","R","T","D","L","L","D","L","T","L"]
slider_time = 10

